### ISSUE TITLE
Plausible chuck corruption

### ISSUE THREAD

**Issue by Alvaroctal** [EpicEricEE/ShopChest#110]
Hi, 

here at our server we got the suspicion of a very, very plausible problem of chunck corruption caused by 1.12.2 version (released on 17/06/2017). Sounds odd, but after some research, all the chucks where there were created shopchests (since the installation of this version) resulted in chunk corruption.

Here you have the error printed in the console constantly:

```
[20:54:03] [Craft Scheduler Thread - 94/WARN]: [ShopChest] Plugin ShopChest v1.12.2 generated an exception while executing task 99
java.lang.IllegalStateException: Asynchronous entity track!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at net.minecraft.server.v1_12_R1.EntityTracker.addEntity(EntityTracker.java:108) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at net.minecraft.server.v1_12_R1.EntityTracker.track(EntityTracker.java:90) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at net.minecraft.server.v1_12_R1.WorldManager.a(WorldManager.java:21) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at net.minecraft.server.v1_12_R1.World.b(World.java:1093) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at net.minecraft.server.v1_12_R1.WorldServer.b(WorldServer.java:1160) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:1125) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at net.minecraft.server.v1_12_R1.Chunk.addEntities(Chunk.java:753) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor$Task.get(AsynchronousExecutor.java:164) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:334) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:131) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:95) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:561) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at org.bukkit.Location.getBlock(Location.java:86) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at de.epiceric.shopchest.utils.ShopUtils.getShop(ShopUtils.java:38) ~[?:?]
	at de.epiceric.shopchest.utils.ShopUtils.getShopsInSight(ShopUtils.java:335) ~[?:?]
	at de.epiceric.shopchest.utils.ShopUtils.updateShops(ShopUtils.java:283) ~[?:?]
	at de.epiceric.shopchest.utils.ShopUtils.updateShops(ShopUtils.java:268) ~[?:?]
	at de.epiceric.shopchest.utils.ShopUpdater.run(ShopUpdater.java:72) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-0869666-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-0869666-03f1e37]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_121]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
```

thanks in advance

Update:

It might be helpful, just installed version 1.12.1, no errors.

**Comment by Alvaroctal** [comment]
Any new information about?

**Comment by EpicEricEE** [comment]
Please try the latest version. It should be fixed there.
