### ISSUE TITLE
Craft Scheduler Thread - 15

### ISSUE THREAD

**Issue by wolfwork** [EpicEricEE/ShopChest#114]
Exception in thread "Craft Scheduler Thread - 15"
[14:51:49 WARN]: org.apache.commons.lang.UnhandledException: Plugin ShopChest v1.12.2 generated an exception while executing task 56
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at org.sqlite.Stmt.executeUpdate(Stmt.java:152)
        at de.epiceric.shopchest.sql.Database$1.run(Database.java:130)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by EpicEricEE** [comment]
I have no idea what is causing this. How often does this error occur?
