### ISSUE TITLE
Error when creating shop

### ISSUE THREAD

**Issue by m4n0fst33l** [EpicEricEE/ShopChest#120]
// Shops appear fine, get this error in terminal though, when rebooting they are gone. the shops.db file //has 0KB written to it (using SQL lite)
//Running latest SaneEconomy and version 1.12.3 of shopchest 

[21:55:22 WARN]: [ShopChest] Plugin ShopChest v1.12.3 generated an exception while executing task 341                                                                              
java.lang.NullPointerException: null                                                                                                                                               
        at de.epiceric.shopchest.sql.Database$6.run(Database.java:375) ~[?:?]                                                                                                      
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.1.12.jar:git-Spigot-b78586d-f3356f1]                                      
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [minecraft_server.1.12.jar:git-Spigot-b78586d-f3356f1]                             
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]                                                                           
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]

**Comment by EpicEricEE** [comment]
Please enable the debug log in the config, reload or restart the server, try again and then send me the contents of the _debug.txt_ file.

**Comment by m4n0fst33l** [comment]
[2017-07-14-1.log.gz](https://github.com/EpicEricEE/ShopChest/files/1149813/2017-07-14-1.log.gz)
Can't find a debug.txt (I enabled it in the server properties and restarted) is this it? I did a test - stop/start, made a shop, stopped server.

**Comment by m4n0fst33l** [comment]
this was made under logs

**Comment by EpicEricEE** [comment]
According to [this](https://hub.spigotmc.org/jira/browse/SPIGOT-2853?focusedCommentId=22521&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22521), this is an issue in SQLite. The problem is that you're running the server on a _musl_-based linux system like _Alpine Linux_. You can try adding the command line parameter ``-Dsqlite.purejava=true`` to the server start script, or if possible change your Linux distribution to one that uses _glibc_ like _Debian_.

**Comment by m4n0fst33l** [comment]
Thanks! that worked - switched to debian and fine!
