### ISSUE TITLE
Weird error (involves craftconomy3)

### ISSUE THREAD

**Issue by NutellaOnBooty** [EpicEricEE/ShopChest#126]
[02:28:07 WARN]: org.h2.jdbc.JdbcSQLException: Scalar subquery contains more than one row; SQL statement:
INSERT INTO cc3_balance(balance, worldName, username_id, currency_id) VALUES(?, ?, (SELECT id from cc3_account WHERE cc3_account.name=? AND bank=?),?) -- (?1, ?2, (SELECT
    ID
FROM PUBLIC.CC3_ACCOUNT
    /* PUBLIC.CC3_ACCOUNT_NAME: NAME = ?3 */
    /* scanCount: 2 */
WHERE (CC3_ACCOUNT.NAME = ?3)
    AND (BANK = ?4)), ?5) [90053-187]
[02:28:07 WARN]:        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
[02:28:07 WARN]:        at org.h2.message.DbException.get(DbException.java:179)
[02:28:07 WARN]:        at org.h2.message.DbException.get(DbException.java:155)
[02:28:07 WARN]:        at org.h2.message.DbException.get(DbException.java:144)
[02:28:07 WARN]:        at org.h2.expression.Subquery.getValue(Subquery.java:41)
[02:28:07 WARN]:        at org.h2.command.dml.Insert.insertRows(Insert.java:143)
[02:28:07 WARN]:        at org.h2.command.dml.Insert.update(Insert.java:114)
[02:28:07 WARN]:        at org.h2.command.CommandContainer.update(CommandContainer.java:78)
[02:28:07 WARN]:        at org.h2.command.Command.executeUpdate(Command.java:254)
[02:28:07 WARN]:        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:157)
[02:28:07 WARN]:        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:143)
[02:28:07 WARN]:        at com.greatmancode.com.zaxxer.libs.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[02:28:07 WARN]:        at com.greatmancode.com.zaxxer.libs.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[02:28:07 WARN]:        at com.greatmancode.craftconomy3.storage.sql.SQLStorageEngine.setBalance(SQLStorageEngine.java:368)
[02:28:07 WARN]:        at com.greatmancode.craftconomy3.account.Account.withdraw(Account.java:213)
[02:28:07 WARN]:        at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.withdrawPlayer(Economy_Craftconomy3.java:295)
[02:28:07 WARN]:        at net.milkbowl.vault.economy.AbstractEconomy.withdrawPlayer(AbstractEconomy.java:45)
[02:28:07 WARN]:        at de.epiceric.shopchest.listeners.ShopInteractListener.create(ShopInteractListener.java:672)
[02:28:07 WARN]:        at de.epiceric.shopchest.listeners.ShopInteractListener.onPlayerInteractCreate(ShopInteractListener.java:310)
[02:28:07 WARN]:        at sun.reflect.GeneratedMethodAccessor160.invoke(Unknown Source)
[02:28:07 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:28:07 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[02:28:07 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296)
[02:28:07 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[02:28:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:498)
[02:28:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:483)
[02:28:07 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234)
[02:28:07 WARN]:        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:448)
[02:28:07 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:911)
[02:28:07 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(SourceFile:55)
[02:28:07 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(SourceFile:11)
[02:28:07 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[02:28:07 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[02:28:07 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[02:28:07 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[02:28:07 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:695)
[02:28:07 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:366)
[02:28:07 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:650)
[02:28:07 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:554)
[02:28:07 WARN]:        at java.lang.Thread.run(Thread.java:745)
[02:28:07 ERROR]: Could not pass event PlayerInteractEvent to ShopChest v1.12.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit-1.12.jar:git-Bukkit-e03b1a5]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.12.jar:git-Bukkit-e03b1a5]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:498) [craftbukkit-1.12.jar:git-Bukkit-e03b1a5]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:483) [craftbukkit-1.12.jar:git-Bukkit-e03b1a5]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [craftbukkit-1.12.jar:git-Bukkit-e03b1a5]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) [craftbukkit-1.12.jar:git-Bukkit-e03b1a5]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:911) [craftbukkit-1.12.jar:git-Bukkit-e03b1a5]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(SourceFile:55) [craftbukkit-1.12.jar:git-Bukkit-e03b1a5]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(SourceFile:11) [craftbukkit-1.12.jar:git-Bukkit-e03b1a5]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.12.jar:git-Bukkit-e03b1a5]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit-1.12.jar:git-Bukkit-e03b1a5]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:695) [craftbukkit-1.12.jar:git-Bukkit-e03b1a5]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:366) [craftbukkit-1.12.jar:git-Bukkit-e03b1a5]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:650) [craftbukkit-1.12.jar:git-Bukkit-e03b1a5]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit-1.12.jar:git-Bukkit-e03b1a5]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: com.greatmancode.craftconomy3.utils.BackendErrorException: Scalar subquery contains more than one row; SQL statement:
INSERT INTO cc3_balance(balance, worldName, username_id, currency_id) VALUES(?, ?, (SELECT id from cc3_account WHERE cc3_account.name=? AND bank=?),?) -- (?1, ?2, (SELECT
    ID
FROM PUBLIC.CC3_ACCOUNT
    /* PUBLIC.CC3_ACCOUNT_NAME: NAME = ?3 */
    /* scanCount: 2 */
WHERE (CC3_ACCOUNT.NAME = ?3)
    AND (BANK = ?4)), ?5) [90053-187]
        at com.greatmancode.craftconomy3.storage.sql.SQLStorageEngine.setBalance(SQLStorageEngine.java:373) ~[?:?]
        at com.greatmancode.craftconomy3.account.Account.withdraw(Account.java:213) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.withdrawPlayer(Economy_Craftconomy3.java:295) ~[?:?]
        at net.milkbowl.vault.economy.AbstractEconomy.withdrawPlayer(AbstractEconomy.java:45) ~[?:?]
        at de.epiceric.shopchest.listeners.ShopInteractListener.create(ShopInteractListener.java:672) ~[?:?]
        at de.epiceric.shopchest.listeners.ShopInteractListener.onPlayerInteractCreate(ShopInteractListener.java:310) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor160.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit-1.12.jar:git-Bukkit-e03b1a5]
        ... 17 more

**Comment by EpicEricEE** [comment]
Did you report this to the CraftConomy developer? I don't think it's an issue of ShopChest.
