### ISSUE TITLE
Spam console with error multiple

### ISSUE THREAD

**Issue by KuroSenseii** [EpicEricEE/ShopChest#146]
In spigot 1.12 last update of shopchest

`[07:44:54] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to ShopChest v1.12.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [Spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [Spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.TileEntityHopper.a(TileEntityHopper.java:369) [Spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.TileEntityHopper.a(TileEntityHopper.java:330) [Spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.TileEntityHopper.o(TileEntityHopper.java:138) [Spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.TileEntityHopper.e(TileEntityHopper.java:119) [Spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1501) [Spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [Spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:814) [Spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [Spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [Spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [Spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.ClassCastException: org.bukkit.block.DoubleChest cannot be cast to org.bukkit.block.Chest
	at de.epiceric.shopchest.listeners.ChestProtectListener.onItemMove(ChestProtectListener.java:275) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor117.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot-1.12.jar:git-Spigot-7228328-af1c013]
	... 14 more`

**Comment by TheZenKitteh** [comment]
Looks about like my error too. Not going to compare piece by piece. I've noticed an error if you try to buy from a shop without the item the shop is wanting to buy. I think that is this error.

**Comment by EpicEricEE** [comment]
Seems to be an issue with double chests. I'll look into it when feel like it.
