### ISSUE TITLE
MySQL Shop Creation in Java 9

### ISSUE THREAD

**Issue by pinkphoenix1990** [EpicEricEE/ShopChest#150]
**Good Day!**

Java 9 is right around the corner, and I have been testing out the plugins that our Minecraft server utilizes on a daily basis. I found that ShopChests provided an exception error when attempting to create a new MySQL database entry when creating shops. 

I know that this is not an enormous concern at this point, but I figured that it would be good to bring the issue to light. Interestingly enough, all of the other database tables were able to both log shop interactions and player logouts, and the shops would remain intact as long as the original person remained online.

Here is the console output:

`09.09 17:43:38 [Server] WARN [ShopChest] Plugin ShopChest v1.12.3 generated an exception while executing task 45 09.09 
17:43:38 [Server] INFO java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter 09.09 17:43:38 [Server] INFO at de.epiceric.shopchest.utils.Utils.encode(Utils.java:403) ~[?:?] 09.09 
17:43:38 [Server] INFO at de.epiceric.shopchest.sql.Database$5.run(Database.java:311) ~[?:?] 09.09 
17:43:38 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-65e8124-9e3636d] 09.09 
17:43:38 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-65e8124-9e3636d] 09.09 
17:43:38 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) [?:?] 09.09 
17:43:38 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) [?:?] 09.09 17:43:38 [Server] INFO at java.lang.Thread.run(Thread.java:844) [?:?] 09.09 
17:43:38 [Server] INFO Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter 09.09 
17:43:38 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?] 09.09 17:43:38 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-65e8124-9e3636d] 09.09 
17:43:38 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-65e8124-9e3636d] 09.09 
17:43:38 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?] 09.09 
17:43:38 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?] 09.09 
17:43:38 [Server] INFO ... 7 more`

Thank you for all your hard work on this amazing plugin!

**Comment by Alvaroctal** [comment]
By the way, startup shows another error with `javax/xml/bind` which is no longer included in java 9 JRE.

```
[13:30:44 WARN]: [ShopChest] Plugin ShopChest v1.12.3 generated an exception while executing task 235
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at de.epiceric.shopchest.utils.Utils.decode(Utils.java:414) ~[?:?]
        at de.epiceric.shopchest.sql.Database$4.run(Database.java:271) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-7754231-a3b3a42]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) [?:?]
        at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
        at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-7754231-a3b3a42]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-7754231-a3b3a42]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
        ... 7 more
```

check: https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by Arrowheads844** [comment]
im a DEV and this is not a problem if you consult this line in the error / warning:  

[Server] INFO java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter. 

This means that that in java 9 they removed the "DatatypeConverter" you can manually install it by running a command in you computer's console, you will have to google it as every computer is different.   If this problem is not fixed it will result in ALL the shops being removed when the server restarts or /shop reload is executed.

**Comment by LeChatP** [comment]
It doesn't a problem btw, just change class but does the same.
org.yaml.snakeyaml.external.biz.base64Coder.Base64Coder class can do the same as DatatypeConverter (only for our case).
I doesn't tried but normally this class can do the trick?

**Comment by EpicEricEE** [comment]
5a4741d
