### ISSUE TITLE
Issue with creating  shop, Shops creates but don't save and then lost on reload

### ISSUE THREAD

**Issue by cursed-techie** [EpicEricEE/ShopChest#163]
[ShopChest] Plugin ShopChest v1.12.3 generated an exception while executing task 18
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at de.epiceric.shopchest.utils.Utils.encode(Utils.java:403) ~[?:?]
        at de.epiceric.shopchest.sql.Database$5.run(Database.java:311) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-95dd097-326c2e6]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-95dd097-326c2e6]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-95dd097-326c2e6]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-95dd097-326c2e6]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 7 more

**Comment by EpicEricEE** [comment]
It's not yet compatible with Java 9.

**Comment by cursed-techie** [comment]
Thanks for the response reverted back to java 8

**Comment by EpicEricEE** [comment]
5a4741d
