### ISSUE TITLE
Error on start (Java 9)

### ISSUE THREAD

**Issue by The947thTokay** [EpicEricEE/ShopChest#168]
Hey there, I've got this error when starting the server:
```
[ShopChest] Plugin ShopChest v1.12.4-${version.git} generated an exception while executing task 21
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at de.epiceric.shopchest.utils.Utils.decode(Utils.java:414) ~[?:?]
        at de.epiceric.shopchest.sql.Database$4.run(Database.java:290) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-70cc382]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-549c1fa-70cc382]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-70cc382]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-70cc382]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 7 more
```
Using Spigot 1.12.2 and got this version of ShopChest by cloning and `mvn clean install`ing. (16-12-17)
Also using Java 9.

**Comment by The947thTokay** [comment]
Woop, looks like this is the same issue as #150 .

**Comment by EpicEricEE** [comment]
5a4741d
