### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by Xierip** [EpicEricEE/ShopChest#169]
> [04:07:33 INFO]: [NoCheatPlus] Post-enable finished.
[04:07:33 INFO]: [XieSkyTab] [INFO] Wait for load worlds
[04:07:33 INFO]: [ASkyBlock] Loading island grid...
[04:07:33 INFO]: [ASkyBlock] Loading islands.yml
[04:07:33 INFO]: [ShopChest] Sprawdzanie aktualizacji...
[04:07:33 INFO]: [ShopChest] Nowy update jest dostepny.
[04:07:34 INFO]: [ASkyBlock] Loading warps...
[04:07:35 INFO]: [ASkyBlock] All files loaded. Ready to play...
[04:07:35 INFO]: [ASkyBlock] Metrics loaded.
[04:07:35 INFO]: [XieSkyTab] [INFO] [RankingTask] Start calculate islands rank (15799 islands)
[04:07:35 INFO]: UUID of player vixsonxd is 4b9a8b0b-3aa3-4104-ab06-905e6ef608b1
[04:07:35 WARN]: [ShopChest] Task #306 for ShopChest v1.12.3 generated an exception
java.lang.NullPointerException: null
        at de.epiceric.shopchest.shop.Shop.getHologramText(Shop.java:188) ~[?:?]
        at de.epiceric.shopchest.shop.Shop.createHologram(Shop.java:160) ~[?:?]
        at de.epiceric.shopchest.shop.Shop.create(Shop.java:84) ~[?:?]
        at de.epiceric.shopchest.utils.ShopUtils$1$1.onResult(ShopUtils.java:242) ~[?:?]
        at de.epiceric.shopchest.utils.Callback$1.run(Callback.java:21) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[paperspigot.jar:git-Paper-1239]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [paperspigot.jar:git-Paper-1239]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [paperspigot.jar:git-Paper-1239]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [paperspigot.jar:git-Paper-1239]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [paperspigot.jar:git-Paper-1239]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [paperspigot.jar:git-Paper-1239]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[04:07:35 WARN]: [ShopChest] Task #308 for ShopChest v1.12.3 generated an exception
java.lang.NullPointerException: null
        at de.epiceric.shopchest.shop.Shop.getHologramText(Shop.java:188) ~[?:?]
        at de.epiceric.shopchest.shop.Shop.createHologram(Shop.java:160) ~[?:?]
        at de.epiceric.shopchest.shop.Shop.create(Shop.java:84) ~[?:?]
        at de.epiceric.shopchest.utils.ShopUtils$1$1.onResult(ShopUtils.java:242) ~[?:?]
        at de.epiceric.shopchest.utils.Callback$1.run(Callback.java:21) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[paperspigot.jar:git-Paper-1239]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [paperspigot.jar:git-Paper-1239]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [paperspigot.jar:git-Paper-1239]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [paperspigot.jar:git-Paper-1239]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [paperspigot.jar:git-Paper-1239]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [paperspigot.jar:git-Paper-1239]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by EpicEricEE** [comment]
AFAIK this only happens with Paper, but it should be fixed with 7874262 (wait for the next update).

**Comment by EpicEricEE** [comment]
Blame Paper for changing stuff that makes plugins incompatible :man_shrugging:
