### ISSUE TITLE
Players unable sell items.

### ISSUE THREAD

**Issue by Dylankjy** [EpicEricEE/ShopChest#176]
This is the stacktrace that is outputted from console when a player is attempting to sell. Please advise:

```
[21:11:51] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ShopChest v1.12.3
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) ~[TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:110) ~[TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:842) ~[TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) [TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at com.iConomy.util.VaultConnector.getBalance(VaultConnector.java:190) ~[?:?]
	at de.epiceric.shopchest.listeners.ShopInteractListener.sell(ShopInteractListener.java:1011) ~[?:?]
	at de.epiceric.shopchest.listeners.ShopInteractListener.handleInteractEvent(ShopInteractListener.java:544) ~[?:?]
	at de.epiceric.shopchest.listeners.ShopInteractListener.onPlayerInteract(ShopInteractListener.java:579) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor715.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[TacoSpigot-1.11.2-b102.jar:git-TacoSpigot-"8aa5e7ec"]
	... 19 more
```

**Comment by seawolff** [comment]
Same.

**Comment by EnDylan** [comment]
Can the plugin author advise. This support ticket has been left unattended for very long.
