### ISSUE TITLE
add disable updater , thanks

### ISSUE THREAD

**Issue by madtomic** [EpicEricEE/ShopChest#181]
[13:44:19 WARN]: [ShopChest] Plugin ShopChest v1.12.3 generated an exception while executing task 103
java.lang.ArrayIndexOutOfBoundsException: 1
        at de.epiceric.shopchest.utils.UpdateChecker.check(UpdateChecker.java:44) ~[?:?]
        at de.epiceric.shopchest.ShopChest$4.run(ShopChest.java:321) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1332]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1332]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1332]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_162]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]

**Comment by EpicEricEE** [comment]
I don't plan on adding a way to disable it, but the error should be fixed with 2ac81b0.
