### ISSUE TITLE
[ISSUE] Database

### ISSUE THREAD

**Issue by Arrowheads844** [EpicEricEE/ShopChest#182]
Please Help, when ever I reload the plugin or restart the server it erases all the shops from the server. Do I have to use a data base?

**Comment by Arrowheads844** [comment]
this is the ERROR [11:39:55 WARN]: [ShopChest] Plugin ShopChest v1.12.3 generated an exception while executing task 105
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at de.epiceric.shopchest.utils.Utils.encode(Utils.java:403) ~[?:?]
	at de.epiceric.shopchest.sql.Database$5.run(Database.java:311) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-c3093ef-7e94e65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-c3093ef-7e94e65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
	... 7 more
>
