### ISSUE TITLE
Start Error

### ISSUE THREAD

**Issue by vr6syncro** [EpicEricEE/ShopChest#196]
`[23:09:52 WARN]: [ShopChest] Plugin ShopChest v1.12.3 generated an exception while executing task 67
java.lang.NullPointerException: null
        at de.epiceric.shopchest.utils.UpdateChecker.check(UpdateChecker.java:43) ~[?:?]
        at de.epiceric.shopchest.ShopChest$4.run(ShopChest.java:321) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-642f6d2-6103339]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-642f6d2-6103339]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_171]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]`

**Comment by Guddina-tim** [comment]
I'm getting this same warning.

**Comment by EpicEricEE** [comment]
2ac81b0
