### ISSUE TITLE
console errors

### ISSUE THREAD

**Issue by GothkittyGirl** [EpicEricEE/ShopChest#202]
04.08 15:42:33 [Server] ERROR Could not pass event PlayerInteractEvent to ShopChest v1.13-SNAPSHOT
04.08 15:42:33 [Server] INFO org.bukkit.event.EventException: null
04.08 15:42:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
04.08 15:42:33 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
04.08 15:42:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
04.08 15:42:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
04.08 15:42:33 [Server] INFO at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:238) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
04.08 15:42:33 [Server] INFO at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:452) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
04.08 15:42:33 [Server] INFO at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1227) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
04.08 15:42:33 [Server] INFO at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
04.08 15:42:33 [Server] INFO at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
04.08 15:42:33 [Server] INFO at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
04.08 15:42:33 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
04.08 15:42:33 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
04.08 15:42:33 [Server] INFO at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
04.08 15:42:33 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
04.08 15:42:33 [Server] INFO at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
04.08 15:42:33 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
04.08 15:42:33 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
04.08 15:42:33 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
04.08 15:42:33 [Server] INFO Caused by: java.lang.NullPointerException

ik this isnt fully working but just want to let you know of this error in console

**Comment by EpicEricEE** [comment]
The error log doesn't seem to be complete. Could you have a look in the latest log file and post the occurrence of this error?

**Comment by GothkittyGirl** [comment]
[10:57:17] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ShopChest v1.13-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:238) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:452) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1227) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NullPointerException
	at de.epiceric.shopchest.listeners.ShopInteractListener.handleInteractEvent(ShopInteractListener.java:400) ~[?:?]
	at de.epiceric.shopchest.listeners.ShopInteractListener.onPlayerInteract(ShopInteractListener.java:640) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor164.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	... 17 more
[10:57:17] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ShopChest v1.13-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:238) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:452) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1227) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NullPointerException
	at de.epiceric.shopchest.listeners.ShopInteractListener.handleInteractEvent(ShopInteractListener.java:400) ~[?:?]
	at de.epiceric.shopchest.listeners.ShopInteractListener.onPlayerInteract(ShopInteractListener.java:640) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor164.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	... 17 more

**Comment by GothkittyGirl** [comment]
i think that 2 of the same error but i thought i would post it for you anyways incase its not

**Comment by EpicEricEE** [comment]
Thank you!
