### ISSUE TITLE
WorldGuard 7

### ISSUE THREAD

**Issue by espidev** [EpicEricEE/ShopChest#216]
Does this plugin have WorldGuard 7 support? I have errors regarding worldguard when I start up the server.

**Comment by espidev** [comment]
[21:21:06] [Server thread/ERROR]: Error occurred while enabling ShopChest v1.12.3 (Is it up to date?)
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;
        at de.epiceric.shopchest.ShopChest.loadExternalPlugins(ShopChest.java:217) ~[?:?]
        at de.epiceric.shopchest.ShopChest.onEnable(ShopChest.java:155) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.13.1.jar:git-Paper-302]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.1.jar:git-Paper-302]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.1.jar:git-Paper-302]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:438) ~[patched_1.13.1.jar:git-Paper-302]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:352) ~[patched_1.13.1.jar:git-Paper-302]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.1.jar:git-Paper-302]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.1.jar:git-Paper-302]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.1.jar:git-Paper-302]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:311) ~[patched_1.13.1.jar:git-Paper-302]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.1.jar:git-Paper-302]

**Comment by james090500** [comment]
Make sure you're using latest build: https://ci.codemc.org/job/EpicEricEE/job/ShopChest/lastStableBuild/
