### ISSUE TITLE
incompatible with worldguard?

### ISSUE THREAD

**Issue by comonier** [EpicEricEE/ShopChest#225]
[01:32:03] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_13_R2.CraftServer] com.sk89q.worldguard.bukkit.WorldGuardPlugin.getFlagRegistry()Lcom/sk89q/worldguard/protection/flags/registry/FlagRegistry; initializing ShopChest v1.12.3 (Is it up to date?)
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getFlagRegistry()Lcom/sk89q/worldguard/protection/flags/registry/FlagRegistry;
	at de.epiceric.shopchest.external.WorldGuardShopFlag.register(WorldGuardShopFlag.java:74) ~[?:?]
	at de.epiceric.shopchest.ShopChest.onLoad(ShopChest.java:116) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-411]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-411]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-411]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by comonier** [comment]
ty so muth
