### ISSUE TITLE
NoClassDefFoundError: com/intellectualcrafters/plot/flag/Flag

### ISSUE THREAD

**Issue by mibby** [EpicEricEE/ShopChest#232]
Paper dev 488 (Spigot 1.13.2)
ShopChest dev 40
PlotSquared-breaking dev 55 (1.13 support version)

@EpicEricEE 
```
# Set whether PlotSquared integration should be enabled
# Of course, this only works if PlotSquared is installed
enable-plotsquared-integration: false
```

```
[04:51:16] [Server thread/INFO]: [ShopChest] Enabling ShopChest v1.13-SNAPSHOT
[04:51:16] [Server thread/ERROR]: Error occurred while enabling ShopChest v1.13-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/flag/Flag
	at de.epiceric.shopchest.ShopChest.loadExternalPlugins(ShopChest.java:279) ~[?:?]
	at de.epiceric.shopchest.ShopChest.onEnable(ShopChest.java:173) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.intellectualcrafters.plot.flag.Flag
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 13 more
[04:51:16] [Server thread/INFO]: [ShopChest] Disabling ShopChest v1.13-SNAPSHOT
[04:51:16] [Server thread/ERROR]: Error occurred while disabling ShopChest v1.13-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
	at de.epiceric.shopchest.ShopChest.onDisable(ShopChest.java:215) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by TheBroTMv2** [comment]
i have the same error seems to be a problem when using spigot 1.13.2

**Comment by EpicEricEE** [comment]
Should be fixed with the latest snapshots.
PlotSquared support will not work for versions _below_ 1.13 anymore!
