### ISSUE TITLE
World guard error

### ISSUE THREAD

**Issue by IchNar** [EpicEricEE/ShopChest#233]
Greedings,
when i started server this error showed to me 
.What does it mean and how can i solve it? Because i cant create shop or do anything.When i create shop it display me in chat that i have to click on chest but when i click on the chest,the chest just open.
Error:
[ERROR] org.codemc.worldguardwrapper.WorldGuardWrapper.registerStateFlag(Ljava/lang/String;Ljava/lang/Boolean;)Z initializing ShopChest v1.13-SNAPSHOT (Is it up to date?)

java.lang.NoSuchMethodError: org.codemc.worldguardwrapper.WorldGuardWrapper.registerStateFlag(Ljava/lang/String;Ljava/lang/Boolean;)Z

at de.epiceric.shopchest.external.WorldGuardShopFlag.register(WorldGuardShopFlag.java:13) ~[?:?]

at de.epiceric.shopchest.ShopChest.onLoad(ShopChest.java:132) ~[?:?]

at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:328) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]

at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]

at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]

**Comment by mechcalvin** [comment]
tested and it has to do with this random tp plugin: https://www.spigotmc.org/resources/wilderness-tp.18431/

**Comment by EpicEricEE** [comment]
Fixed in latest snapshots (although all custom shop flags seem to always be denied at the moment)
