### ISSUE TITLE
MySQL connection seems to be closed before logging to db

### ISSUE THREAD

**Issue by Lbleu** [EpicEricEE/ShopChest#24]
Hi again, I'm using the latest version of the plugin. Shops loading and selling items to them works well
Debug log:
```
[20/08/2016 03:04:50] Lbleu wants to sell
[20/08/2016 03:04:50] Lbleu is selling (#30)
[20/08/2016 03:04:50] Vendor has enough money for 0 item(s) (#30)
[20/08/2016 03:04:50] Chest has enough inventory space for 1728 items (#30)
[20/08/2016 03:04:50] Removing items from inventory...
[20/08/2016 03:04:50] Lbleu successfully sold (#30)
[20/08/2016 03:04:50] Failed to log economy transaction to database
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 41,473 milliseconds ago.  The last packet sent successfully to the server was 1 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:983)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3457)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3357)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3797)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
	at de.epiceric.shopchest.sql.Database$1.run(Database.java:344)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2949)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3367)
	... 16 more
[20/08/2016 03:04:53] Lbleu wants to sell
[20/08/2016 03:04:53] Lbleu is selling (#30)
[20/08/2016 03:04:53] Vendor has enough money for 0 item(s) (#30)
[20/08/2016 03:04:53] Chest has enough inventory space for 1728 items (#30)
[20/08/2016 03:04:53] Removing items from inventory...
[20/08/2016 03:04:53] Lbleu successfully sold (#30)
[20/08/2016 03:04:53] Failed to log economy transaction to database
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1237)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1232)
	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4131)
	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4100)
	at de.epiceric.shopchest.sql.Database$1.run(Database.java:331)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link 
```failure

**Comment by EpicEricEE** [comment]
Please try [this version](https://goo.gl/I5WNNf) and tell me if it's fixed. You will probably still get an error message, but the economy transaction should be logged in the database. If it doesn't work, you can try decreasing the _ping-interval_ in the configuration file of ShopChest and/or increasing the timeouts _(interactive_timeout, wait_timeout)_ in the configuration of your MySQL server.

**Comment by Lbleu** [comment]
Now it works and as you said, still shows an error on console
