### ISSUE TITLE
I got this error message, i using paperspigot 1.12.2

### ISSUE THREAD

**Issue by Pledix** [EpicEricEE/ShopChest#240]
`[12:31:00 WARN]: [ShopChest] Plugin ShopChest v1.12.3 generated an exception while executing task 81
java.lang.NullPointerException: null
        at de.epiceric.shopchest.utils.UpdateChecker.check(UpdateChecker.java:43) ~[?:?]
        at de.epiceric.shopchest.ShopChest$4.run(ShopChest.java:321) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[paperclip-1596.jar:git-Paper-1596]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[paperclip-1596.jar:git-Paper-1596]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paperclip-1596.jar:git-Paper-1596]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]`

**Comment by EpicEricEE** [comment]
Update checker was not working. Fixed already in snapshots.
