### ISSUE TITLE
ShopChest on old API, breaks when PlotSquared is being used.

### ISSUE THREAD

**Issue by mrfloris** [EpicEricEE/ShopChest#245]
Using the latest worldguard/worldedit/plotsquared/spigot and shopchest, it's always shopchest that breaks when we use plotsquared. When reporting this to plotsquared they say this shopchest plugin is on an outdated api and needs to get updated.

I'd love a fix if possible.

```
[00:30:12 INFO]: [ShopChest] Enabling ShopChest v1.13-SNAPSHOT
[00:30:12 ERROR]: Error occurred while enabling ShopChest v1.13-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/flag/Flag
	at de.epiceric.shopchest.ShopChest.loadExternalPlugins(ShopChest.java:279) ~[?:?]
	at de.epiceric.shopchest.ShopChest.onEnable(ShopChest.java:173) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.intellectualcrafters.plot.flag.Flag
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 13 more
```

```
>about
[00:31:48 INFO]: This server is running CraftBukkit version git-Spigot-b0f4c22-c7ba979 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

>about ShopChest
[00:31:51 INFO]: ShopChest version 1.13-SNAPSHOT
[00:31:51 INFO]: Create your own nice-looking chest shops and sell your stuff to other players!
[00:31:51 INFO]: Website: https://www.spigotmc.org/resources/shopchest.11431/
[00:31:51 INFO]: Author: EpicEric

>about PlotSquared
[00:31:53 INFO]: PlotSquared version 4.152
[00:31:53 INFO]: Easy, yet powerful Plot World generation and management.

[00:31:53 INFO]: Authors: Citymonstret, Empire92, MattBDev and dordsor21

>
```

ShopChest config yml
```
# Set whether PlotSquared integration should be enabled
# Of course, this only works if PlotSquared is installed
enable-plotsquared-integration: false
```

The setting was already false, but this still happens.

**Comment by turtlshell** [comment]
+1, also having the same conflict.

12.02 00:52:20 [Server] ERROR Error occurred while enabling ShopChest v1.13-SNAPSHOT (Is it up to date?)
12.02 00:52:20 [Server] INFO java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/flag/Flag
12.02 00:52:20 [Server] INFO at de.epiceric.shopchest.ShopChest.loadExternalPlugins(ShopChest.java:279) ~[?:?]
12.02 00:52:20 [Server] INFO at de.epiceric.shopchest.ShopChest.onEnable(ShopChest.java:173) ~[?:?]
12.02 00:52:20 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
12.02 00:52:20 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.intellectualcrafters.plot.flag.Flag
12.02 00:52:20 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
12.02 00:52:20 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
12.02 00:52:20 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
12.02 00:52:20 [Server] INFO ... 13 more
12.02 00:52:20 [Server] INFO Disabling ShopChest v1.13-SNAPSHOT
12.02 00:52:20 [Server] ERROR Error occurred while disabling ShopChest v1.13-SNAPSHOT (Is it up to date?)
12.02 00:52:20 [Server] INFO java.lang.NullPointerException: null
12.02 00:52:20 [Server] INFO at de.epiceric.shopchest.ShopChest.onDisable(ShopChest.java:215) ~[?:?]
12.02 00:52:20 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:330) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-522]
12.02 00:52:20 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by mrfloris** [comment]
Thank you for fixing the dependency.
