### ISSUE TITLE
Could not find any Vault economy dependency!

### ISSUE THREAD

**Issue by Blueeyestar** [EpicEricEE/ShopChest#257]
Spigot-Ver:CraftBukkit version git-Spigot-8043ebc-89c52b7 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

**in the newest 1.14.1 is the newest Vault inside. Also recognized by almost all plugins only shopchest seems to have some problems with it**

[07:02:15] [Server thread/INFO]: [ShopChest] Enabling ShopChest v1.13-SNAPSHOT
[07:02:15] [Server thread/ERROR]: [ShopChest] 
[07:02:15] [Server thread/INFO]: [ShopChest] Disabling ShopChest v1.13-SNAPSHOT
[07:02:15] [Server thread/ERROR]: Error occurred while disabling ShopChest v1.13-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
	at de.epiceric.shopchest.ShopChest.onDisable(ShopChest.java:218) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:377) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at de.epiceric.shopchest.ShopChest.onEnable(ShopChest.java:151) [ShopChest-1.13-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by EpicEricEE** [comment]
You need to install an economy plugin that hooks into Vault (most economy plugins do), Vault alone does not suffice.

**Comment by Blueeyestar** [comment]
You're absolutely right. Nice that your plugin is compatible. There you can see that it is well written :)
