### ISSUE TITLE
Plugin generated an exception while executing task 57

### ISSUE THREAD

**Issue by Lapotor** [EpicEricEE/ShopChest#26]
Hey i think that the Plugin need apache but when i do please add it to the Plugin Page.
The Error:
```
[pool-3-thread-8/WARN]: org.apache.commons.lang.UnhandledException: Plugin ShopChest v1.10.3 generated an exception while executing task 57
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
	at de.epiceric.shopchest.language.LanguageUtils.getMessage(LanguageUtils.java:1097)
	at de.epiceric.shopchest.ShopChest$7.run(ShopChest.java:254)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.ChatColor
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 7 more
```
If you have any questions to me you can come to our TeamSpeak3 Server **reden.teamspeak3.de** _(German)_ and look after me or ask someone
I hope you can fix or answer it!?

**Comment by EpicEricEE** [comment]
Use spigot instead of craftbukkit. Will be fixed in the next version (684a0b3c).

**Comment by Lapotor** [comment]
When do you bring out the new version (do you planed that)?

**Comment by Lapotor** [comment]
I can't use Spigot the Hosting Provider do not support it till yet

**Comment by MineTheCube** [comment]
I compiled it for you: [ShopChest.zip](https://github.com/EpicEricEE/ShopChest/files/455185/ShopChest.zip)
