### ISSUE TITLE
Shop holograms disappearing

### ISSUE THREAD

**Issue by Snewmy** [EpicEricEE/ShopChest#280]
Hello, There seems to be an issue with shop holograms just randomly disappearing, with an error in the console. All shop holograms turn off all at once, and only a /shop reload will fix it (temporarily til it happens again)

[00:38:15 WARN]: Exception in thread "Shop Updater" java.lang.NullPointerException
[00:38:15 WARN]: at de.epiceric.shopchest.nms.JsonBuilder.parse(JsonBuilder.java:197)
[00:38:15 WARN]: at de.epiceric.shopchest.utils.Utils.createDataWatcher(Utils.java:450)
[00:38:15 WARN]: at de.epiceric.shopchest.nms.ArmorStandWrapper.setVisible(ArmorStandWrapper.java:37)
[00:38:15 WARN]: at de.epiceric.shopchest.nms.Hologram.togglePlayer(Hologram.java:165)
[00:38:15 WARN]: at de.epiceric.shopchest.nms.Hologram.showPlayer(Hologram.java:115)
[00:38:15 WARN]: at de.epiceric.shopchest.nms.Hologram.showPlayer(Hologram.java:106)
[00:38:15 WARN]: at de.epiceric.shopchest.utils.ShopUtils.updateVisibleShops(ShopUtils.java:409)
[00:38:15 WARN]: at de.epiceric.shopchest.utils.ShopUtils.updateShops(ShopUtils.java:336)
[00:38:15 WARN]: at de.epiceric.shopchest.utils.ShopUtils.updateShops(ShopUtils.java:321)
[00:38:15 WARN]: at de.epiceric.shopchest.utils.ShopUpdater.lambda$updateShops$1(ShopUpdater.java:71)
[00:38:15 WARN]: at de.epiceric.shopchest.utils.ShopUpdater.lambda$start$0(ShopUpdater.java:30)
[00:38:15 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by EpicEricEE** [comment]
Could you show me your hologram format file?

**Comment by Snewmy** [comment]
Sure! 
https://hasteb.in/xonokowe.shell
