### ISSUE TITLE
Plugin not working anymore. Connection closed on server startup

### ISSUE THREAD

**Issue by 4Cris** [EpicEricEE/ShopChest#281]
Here is the code from the debug file:

[05/09/2019 01:39:10] Loading ShopChest version 1.13-SNAPSHOT
[05/09/2019 01:39:10] Flag create-shop: true
[05/09/2019 01:39:10] Flag use-shop: true
[05/09/2019 01:39:10] Flag use-admin-shop: true
[05/09/2019 01:39:56] Enabling ShopChest version 1.13-SNAPSHOT
[05/09/2019 01:39:56] Creating plugin command
[05/09/2019 01:39:56] Adding sub command "create"
[05/09/2019 01:39:56] Adding sub command "remove"
[05/09/2019 01:39:56] Adding sub command "info"
[05/09/2019 01:39:56] Adding sub command "limits"
[05/09/2019 01:39:56] Adding sub command "open"
[05/09/2019 01:39:56] Adding sub command "removeall"
[05/09/2019 01:39:56] Adding sub command "reload"
[05/09/2019 01:39:56] Adding sub command "update"
[05/09/2019 01:39:56] Adding sub command "config"
[05/09/2019 01:39:56] Registering command shop
[05/09/2019 01:39:56] Registered custom PlotSquared flags
[05/09/2019 01:39:56] Initializing Metrics...
[05/09/2019 01:39:56] Using database type: MySQL
[05/09/2019 01:39:56] Registering listeners...
[05/09/2019 01:39:56] Initializing Shops...
[05/09/2019 01:39:56] Reloading shops...
[05/09/2019 01:40:03] Cleaned up economy log
[05/09/2019 01:40:03] Initialized database with 1509 entries
[05/09/2019 01:40:04] Reloading shops...
[05/09/2019 01:40:04] Failed to get shops
java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
	at de.epiceric.shopchest.dependencies.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
	at de.epiceric.shopchest.sql.Database$3.run(Database.java:379)
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[05/09/2019 01:40:05] Cleaned up economy log
[05/09/2019 01:40:05] Initialized database with 1509 entries
[05/09/2019 01:40:05] Disabling ShopChest...
[05/09/2019 01:40:05] Stopping updater

**Comment by EpicEricEE** [comment]
Should be fixed with [build 83](https://ci.codemc.io/job/EpicEricEE/job/ShopChest/). Leave a message if that is not the case.
