### ISSUE TITLE
Invisible Armor Stands from 1.12

### ISSUE THREAD

**Issue by Buzzbugs** [EpicEricEE/ShopChest#283]
Hello, we are on 1.14.4 now and started fresh with ShopChests however it seems some shops are still floating around from when we used the plugin in 1.12 with no way to remove them. Any suggestions much appreciated, thanks! 

![invisible stand](https://user-images.githubusercontent.com/54085800/64485006-d478f880-d25d-11e9-8aa8-63563ade2653.jpg)

**Comment by C4338** [comment]
I have the same problem using Spigot 1.12.2
When I start the server I get this error:

[16:19:08 WARN]: [ShopChest] Plugin ShopChest v1.12.2 generated an exception while executing task 43
java.lang.NullPointerException: null
        at de.epiceric.shopchest.utils.UpdateChecker.check(UpdateChecker.java:43) ~[?:?]
        at de.epiceric.shopchest.ShopChest$4.run(ShopChest.java:321) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
