### ISSUE TITLE
crash on Glowstone

### ISSUE THREAD

**Issue by tsao-chi** [EpicEricEE/ShopChest#301]
```
01:13:31 [INFO] Enabling ShopChest v1.13-SNAPSHOT
01:13:31 [WARNING] Server version not officially supported: glowstone!
01:13:31 [WARNING] Plugin may still work, but more errors are expected!
01:13:31 [SEVERE] Error occurred while enabling ShopChest v1.13-SNAPSHOT (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at de.epiceric.shopchest.utils.Utils.getMajorVersion(Utils.java:617)
	at de.epiceric.shopchest.language.LanguageUtils.load(LanguageUtils.java:1002)
	at de.epiceric.shopchest.ShopChest.onEnable(ShopChest.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
	at net.glowstone.GlowServer.enablePlugins(GlowServer.java:1346)
	at net.glowstone.GlowServer.start(GlowServer.java:819)
	at net.glowstone.GlowServer.run(GlowServer.java:625)
	at net.glowstone.GlowServer.main(GlowServer.java:489)
01:13:31 [INFO] Disabling ShopChest v1.13-SNAPSHOT
```

**Comment by EpicEricEE** [comment]
I can't use the same method for version detection with Glowstone as with Spigot/Paper, so it isn't supported at the moment.
