### ISSUE TITLE
No hologram, non-removable armor stands.

### ISSUE THREAD

**Issue by VKartze** [EpicEricEE/ShopChest#307]
SethBling's heaven.
![2020-02-26_03 12 50](https://user-images.githubusercontent.com/41291372/75283702-ef5c1b00-5845-11ea-8971-9ca2f8033f54.png)
According to plugin.yml, I'm using ShopChest 1.12.3.
Server version: git-Paper-118 (MC: 1.15.2)
A piece of log:
```
[INFO] .... AmadeusDream issued server command: /shop create 1 0 10
[ERROR] .... [ShopChest] Failed to create line for hologram
[ERROR] .... [ShopChest] Failed to create line for hologram
[ERROR] .... [ShopChest] Failed to create line for hologram
[ERROR] .... [ShopChest] Failed to create line for hologram
[ERROR] .... [ShopChest] Failed to create shop item
[INFO] .... AmadeusDream issued server command: /shop remove
[ERROR] .... [ShopChest] Could not remove hologram
[ERROR] .... [ShopChest] Could not remove hologram
[ERROR] .... [ShopChest] Could not remove hologram
[ERROR] .... [ShopChest] Could not remove hologram
```
Every reload, right after "Done!":
```
[ShopChest] Plugin ShopChest v1.12.3 generated an exception while executing task 20
java.lang.NullPointerException: null
at de.epiceric.shopchest.utils.UpdateChecker.check(UpdateChecker.java:43) ~[?:?]
at de.epiceric.shopchest.ShopChest$4.run(ShopChest.java:321) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-120]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-120]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-120]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
```

**Comment by VKartze** [comment]
Ooops, sorry. My mistake. Switched to dev build and it seems no issues here.
