### ISSUE TITLE
Plugin doesn't work on Paper 1.12.2

### ISSUE THREAD

**Issue by ItzAmirreza** [EpicEricEE/ShopChest#309]
Hi, Here is an error and I don't know why this great plugin is not working on my server. This happens while loading the plugin.
```
[17:27:59] [Craft Scheduler Thread - 20/WARN]: [ShopChest] Plugin ShopChest v1.12.3 generated an exception while executing task 141
java.lang.NullPointerException: null
	at de.epiceric.shopchest.utils.UpdateChecker.check(UpdateChecker.java:43) ~[?:?]
	at de.epiceric.shopchest.ShopChest$4.run(ShopChest.java:321) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[paper.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[paper.jar:git-Paper-1618]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper.jar:git-Paper-1618]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]

```

**Comment by EpicEricEE** [comment]
That's just the update checker. The plugin should work fine, you may want to update to a [snapshot build](https://ci.codemc.io/job/EpicEricEE/job/ShopChest/) though since the official release has not been updated since 2017.

**Comment by ItzAmirreza** [comment]
No, but it really does not work, I changed the main command to pshop and when I execute it in-game I get a default spigot message which says there is no command like this and it's like ShopChest did not load at all.

**Comment by EpicEricEE** [comment]
Then there is probably another error message somewhere in the console.
