### ISSUE TITLE
Error  [ShopChest]

### ISSUE THREAD

**Issue by MCScorpions** [EpicEricEE/ShopChest#349]
please help udpate 1.16.4 ERROR]: [ShopChest] Could not change hologram visibility and [22:23:23 ERROR]: [ShopChest] Failed to create item!

**Comment by 42Atomys** [comment]
I can confirm the error `java[28921]: [17:38:35 ERROR]: [ShopChest] Could not change hologram visibility` is linked to 1.16.4 update. 

In case of error message, the in-game render oh hologram is curious 

![image](https://user-images.githubusercontent.com/8448358/98455328-5967e680-216f-11eb-93f0-59bf4f333154.png)

**Comment by 42Atomys** [comment]
Add more informations about it, this is debug messages :
```
[08/11/2020 16:22:42] Failed to create item!
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedConstructorAccessor71.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at de.epiceric.shopchest.shop.ShopItem.showPlayer(ShopItem.java:96)
        at de.epiceric.shopchest.shop.ShopItem.showPlayer(ShopItem.java:83)
        at de.epiceric.shopchest.utils.ShopUtils.updateVisibleShops(ShopUtils.java:469)
        at de.epiceric.shopchest.utils.ShopUtils.updateShops(ShopUtils.java:405)
        at de.epiceric.shopchest.utils.ShopUtils.updateShops(ShopUtils.java:390)
        at de.epiceric.shopchest.utils.ShopUpdater.lambda$updateShops$1(ShopUpdater.java:72)
        at de.epiceric.shopchest.utils.ShopUpdater.lambda$start$0(ShopUpdater.java:31)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_16_R3.PacketPlayOutEntityMetadata.<init>(SourceFile:21)
        ... 11 more


[08/11/2020 16:22:48] Could not change armor stand visibility
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedConstructorAccessor71.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at de.epiceric.shopchest.nms.ArmorStandWrapper.setVisible(ArmorStandWrapper.java:41)
        at de.epiceric.shopchest.nms.Hologram.togglePlayer(Hologram.java:141)
        at de.epiceric.shopchest.nms.Hologram.showPlayer(Hologram.java:92)
        at de.epiceric.shopchest.nms.Hologram.showPlayer(Hologram.java:83)
        at de.epiceric.shopchest.utils.ShopUtils.updateVisibleShops(ShopUtils.java:478)
        at de.epiceric.shopchest.utils.ShopUtils.updateShops(ShopUtils.java:405)
        at de.epiceric.shopchest.utils.ShopUtils.updateShops(ShopUtils.java:390)
        at de.epiceric.shopchest.utils.ShopUpdater.lambda$updateShops$1(ShopUpdater.java:72)
        at de.epiceric.shopchest.utils.ShopUpdater.lambda$start$0(ShopUpdater.java:31)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_16_R3.PacketPlayOutEntityMetadata.<init>(SourceFile:21)
        ... 13 more
```

**Comment by mechcalvin** [comment]
same here, waiting for a fix

**Comment by 42Atomys** [comment]
I add the support for 1.16.4,
wait pull request approval :) 

https://github.com/EpicEricEE/ShopChest/pull/351
