### ISSUE TITLE
Holograms not appearing in 1.17

### ISSUE THREAD

**Issue by Shanman150** [EpicEricEE/ShopChest#368]
We launched our summer server in 1.17 and went back to use our favorite shop plugin, ShopChest. It's still got all the functionality, but probably due to the new items, the holograms are missing. I've got signs up designating what each shop sells, but are there plans to fix the hologram issue? (Or is the hologram issue on my side?)

Error message on server launch:
[26.06 16:02:32] [Server] [Server thread/WARN]: [ShopChest] Task #92 for ShopChest v1.13-SNAPSHOT generated an exception
[26.06 16:02:32] [Server] java.lang.NullPointerExceptionCannot invoke "java.lang.Class.getConstructor(java.lang.Class[])" because "this.packetPlayOutEntityTeleportClass" is null
[26.06 16:02:32] [Server] 	at de.epiceric.shopchest.nms.ArmorStandWrapper.setLocation(ArmorStandWrapper.java:55) ~[?:?]
[26.06 16:02:32] [Server] 	at de.epiceric.shopchest.nms.Hologram.addLine(Hologram.java:181) ~[?:?]
[26.06 16:02:32] [Server] 	at de.epiceric.shopchest.nms.Hologram.addLine(Hologram.java:166) ~[?:?]
[26.06 16:02:32] [Server] 	at de.epiceric.shopchest.nms.Hologram.<init>(Hologram.java:31) ~[?:?]
[26.06 16:02:32] [Server] 	at de.epiceric.shopchest.shop.Shop$1.run(Shop.java:234) ~[?:?]
[26.06 16:02:32] [Server] 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
[26.06 16:02:32] [Server] 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
[26.06 16:02:32] [Server] 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1252) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
[26.06 16:02:32] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
[26.06 16:02:32] [Server] 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
[26.06 16:02:32] [Server] 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
[26.06 16:02:32] [Server] 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
[26.06 16:02:32] [Server] 	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Bobbbe** [comment]
i have similar error , Paper 1.17 whene im login to server and im create shop. very nice plugin ! good job and thx for update all the time :) have a nice day.

[16:45:19 ERROR]: Could not pass event PlayerJoinEvent to ShopChest v1.13-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getMethod(String, java.lang.Class[])" because "this.chatSerializerClass" is null
        at de.epiceric.shopchest.nms.JsonBuilder.sendJson(JsonBuilder.java:240) ~[?:?]
        at de.epiceric.shopchest.utils.Utils.sendUpdateMessage(Utils.java:335) ~[?:?]
        at de.epiceric.shopchest.listeners.NotifyPlayerOnJoinListener.onPlayerJoin(NotifyPlayerOnJoinListener.java:33) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor395.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Paper-53]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:357) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:299) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:308) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:399) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:196) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1576) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-53]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[16:45:19 INFO]: [Bank] Loading d85a54a8-165f-4a90-aefa-0531a7146123
[16:45:19 INFO]: Gobbber[/192.168.2.10:62531] logged in with entity id 476 at ([Survie]260.01035291941633, 88.0, -154.46696406818901)
[16:45:19 WARN]: [Essentials] Permissions lag notice with (LuckPermsHandler). Response took 33,383200ms. Summary: Getting prefix for Gobbber
[16:45:19 INFO]:  [+] Gobbber
[16:45:20 INFO]: [Bank] Loaded d85a54a8-165f-4a90-aefa-0531a7146123 after 1202ms
[16:46:47 INFO]: Gobbber issued server command: /shopchest:shop create 1 5 0
[16:46:51 WARN]: Exception in thread "Shop Updater" java.lang.NullPointerException: Cannot invoke "java.lang.Class.getConstructor(java.lang.Class[])" because "dataWatcherClass" is null
[16:46:51 WARN]:        at de.epiceric.shopchest.utils.Utils.createDataWatcher(Utils.java:382)
[16:46:51 WARN]:        at de.epiceric.shopchest.shop.ShopItem.showPlayer(ShopItem.java:94)
[16:46:51 WARN]:        at de.epiceric.shopchest.shop.ShopItem.showPlayer(ShopItem.java:83)
[16:46:51 WARN]:        at de.epiceric.shopchest.utils.ShopUtils.updateVisibleShops(ShopUtils.java:483)
[16:46:51 WARN]:        at de.epiceric.shopchest.utils.ShopUtils.updateShops(ShopUtils.java:419)
[16:46:51 WARN]:        at de.epiceric.shopchest.utils.ShopUtils.updateShops(ShopUtils.java:404)
[16:46:51 WARN]:        at de.epiceric.shopchest.utils.ShopUpdater.lambda$updateShops$2(ShopUpdater.java:83)
[16:46:51 WARN]:        at de.epiceric.shopchest.utils.ShopUpdater.lambda$start$0(ShopUpdater.java:31)
[16:46:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[16:46:51 WARN]: [ShopChest] Task #1754 for ShopChest v1.13-SNAPSHOT generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getConstructor(java.lang.Class[])" because "this.packetPlayOutEntityTeleportClass" is null
        at de.epiceric.shopchest.nms.ArmorStandWrapper.setLocation(ArmorStandWrapper.java:55) ~[?:?]
        at de.epiceric.shopchest.nms.Hologram.addLine(Hologram.java:181) ~[?:?]
        at de.epiceric.shopchest.nms.Hologram.addLine(Hologram.java:166) ~[?:?]
        at de.epiceric.shopchest.nms.Hologram.<init>(Hologram.java:31) ~[?:?]
        at de.epiceric.shopchest.shop.Shop$1.run(Shop.java:234) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-53]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-53]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by mrfloris** [comment]
Same, we'd love to get plotsquared 6, new we/wg support and of course paper 1.17 support.
