### ISSUE TITLE
Plugin requires a bump to support 1.18

### ISSUE THREAD

**Issue by mrfloris** [EpicEricEE/ShopChest#375]
Mojang has announced 1.18 to be their latest version, Spigot and Paper have 1.18 builds out now. Please note that Mojang now requires Java 17 for 1.18

The latest build from https://ci.codemc.io/job/EpicEricEE/job/ShopChest/ doesn't load, causes the following error:
```
[10:04:47 INFO]: [ShopChest] Enabling ShopChest v1.13-SNAPSHOT
[10:04:47 ERROR]: Error occurred while enabling ShopChest v1.13-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class de.epiceric.shopchest.utils.Utils
    at de.epiceric.shopchest.ShopChest.onEnable(ShopChest.java:175) ~[ShopChest-1.13-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.18.jar:git-Paper-17]
    at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.18.jar:git-Paper-17]
    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:726) ~[paper-1.18.jar:git-Paper-17]
    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:501) ~[paper-1.18.jar:git-Paper-17]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.jar:git-Paper-17]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[paper-1.18.jar:git-Paper-17]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.jar:git-Paper-17]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:04:47 INFO]: [ShopChest] Disabling ShopChest v1.13-SNAPSHOT
```
If you need more information feel free to ask.

**Comment by MCScorpions** [comment]
**please update plugin version 1.18 + thx**

**Comment by StKillReal** [comment]
Need an update to 1.18

**Comment by mrfloris** [comment]
Friendly bump after a week. 

Update: Paper 1.18.1 has been released. We're ready to go live.

**Comment by StKillReal** [comment]
So, seems like plugin is abandoned and developer is just don't care about it anymore

**Comment by mrfloris** [comment]
> So, seems like plugin is abandoned and developer is just don't care about it anymore

Not something you should just assume. For all we know they've been dealing with covid in the family, or even loss. Or yes, maybe they have moved on to other things. Their personal life is not our business, but yes, it sucks for us. 

Thankfully it's open source, hopefully either the author lets us know he's abandoned it and we can contact a dev somewhere else, or we try to PR ourselves (i tried, i failed..)

**Comment by Niko302** [comment]
> > So, seems like plugin is abandoned and developer is just don't care about it anymore
> 
> Not something you should just assume. For all we know they've been dealing with covid in the family, or even loss. Or yes, maybe they have moved on to other things. Their personal life is not our business, but yes, it sucks for us.
> 
> Thankfully it's open source, hopefully either the author lets us know he's abandoned it and we can contact a dev somewhere else, or we try to PR ourselves (i tried, i failed..)

Any update on getting a development build for this or should I hire someone to try and get it up and working ?

**Comment by EpicEricEE** [comment]
Hey there, sorry for not responding.

I don't think I will get to updating this anytime soon. I'd be happy if someone can be found to fork and further maintain this plugin. However, as past updates have mostly been done in a not very thoughtful way, the code has over time become messier and more painful to maintain, so restructuring some parts the project and especially dropping support for old Minecraft versions would likely be very helpful. There are already some forks that fixed or improved parts of that mess, though I didn't yet find any "officially" published versions.

**Comment by mrfloris** [comment]
Ah, it is so nice to at least hear something. Now we know where we stand. 
I am sorry to hear it got so messy that you didn't or can't work on it anymore. I guess it's official. This is not something we can use or recommend on production. Shame, I always enjoyed it. 

By the time someone cleaned this up it is time for 1.19 probably, I need a solution today. Will purge, and move to something else. 

Best of luck eric and thank you for the years we got to use this.
