### ISSUE TITLE
Hologram was dissapered after ConcurrentModificationException throwed

### ISSUE THREAD

**Issue by ken-kentan** [EpicEricEE/ShopChest#376]
```
[17:48:20] [Shop Updater/WARN]: Exception in thread "Shop Updater" java.util.ConcurrentModificationException
[17:48:20] [Shop Updater/WARN]: 	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
[17:48:20] [Shop Updater/WARN]: 	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
[17:48:20] [Shop Updater/WARN]: 	at ShopChest-1.13-SNAPSHOT.jar//de.epiceric.shopchest.nms.Hologram.togglePlayer(Hologram.java:140)
[17:48:20] [Shop Updater/WARN]: 	at ShopChest-1.13-SNAPSHOT.jar//de.epiceric.shopchest.nms.Hologram.showPlayer(Hologram.java:92)
[17:48:20] [Shop Updater/WARN]: 	at ShopChest-1.13-SNAPSHOT.jar//de.epiceric.shopchest.nms.Hologram.showPlayer(Hologram.java:83)
[17:48:20] [Shop Updater/WARN]: 	at ShopChest-1.13-SNAPSHOT.jar//de.epiceric.shopchest.utils.ShopUtils.updateVisibleShops(ShopUtils.java:492)
[17:48:20] [Shop Updater/WARN]: 	at ShopChest-1.13-SNAPSHOT.jar//de.epiceric.shopchest.utils.ShopUtils.updateShops(ShopUtils.java:419)
[17:48:20] [Shop Updater/WARN]: 	at ShopChest-1.13-SNAPSHOT.jar//de.epiceric.shopchest.utils.ShopUtils.updateShops(ShopUtils.java:404)
[17:48:20] [Shop Updater/WARN]: 	at ShopChest-1.13-SNAPSHOT.jar//de.epiceric.shopchest.utils.ShopUpdater.lambda$updateShops$1(ShopUpdater.java:72)
[17:48:20] [Shop Updater/WARN]: 	at ShopChest-1.13-SNAPSHOT.jar//de.epiceric.shopchest.utils.ShopUpdater.lambda$start$0(ShopUpdater.java:31)
[17:48:20] [Shop Updater/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by mrfloris** [comment]
Which server engine and java version are you using?

**Comment by ken-kentan** [comment]
Paper 1.17.1
Java 16

**Comment by mrfloris** [comment]
On java 11+ to java 17 on 1.17.1, this build 104 works for me with older holographi display plugin (not the new one for 1.18)
https://ci.codemc.io/job/EpicEricEE/job/ShopChest/104/

**Comment by ken-kentan** [comment]
Yeah. In usually, This issue isn't happen.
The exception will be throwen in rare case.
