### ISSUE TITLE
Error on Plugin enable

### ISSUE THREAD

**Issue by vxnsin** [EpicEricEE/ShopChest#382]
I Install ShopChest on a 1.15.2 Paperspigot Minecraft Server 
The Error is:
![image](https://user-images.githubusercontent.com/51481323/156880766-326c32fb-d77b-4f5d-8863-1e3d70142d73.png)

**Comment by coolternet** [comment]
same thing on 1.21.11

`[02:29:14] [Server thread/INFO]: [ShopChest] Enabling ShopChest v1.12.3*
[02:29:14] [Server thread/WARN]: [ShopChest] Server version not officially supported: craftbukkit!
[02:29:14] [Server thread/WARN]: [ShopChest] Plugin may still work, but more errors are expected!
[02:29:14] [Server thread/ERROR]: Error occurred while enabling ShopChest v1.12.3 (Is it up to date?)
java.lang.NoSuchMethodError: 'com.sk89q.worldguard.protection.managers.RegionManager com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(org.bukkit.World)'
	at ShopChest.jar//de.epiceric.shopchest.ShopChest.loadExternalPlugins(ShopChest.java:217) ~[?:?]
	at ShopChest.jar//de.epiceric.shopchest.ShopChest.onEnable(ShopChest.java:155) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.21.11-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.11.jar:1.21.11-100-4873e3f]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.11.jar:1.21.11-100-4873e3f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.11-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.21.11.jar:1.21.11-100-4873e3f]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:596) ~[paper-1.21.11.jar:1.21.11-100-4873e3f]
	at net.minecraft.server.MinecraftServer.initPostWorld(MinecraftServer.java:636) ~[paper-1.21.11.jar:1.21.11-100-4873e3f]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:365) ~[paper-1.21.11.jar:1.21.11-100-4873e3f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1258) ~[paper-1.21.11.jar:1.21.11-100-4873e3f]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:388) ~[paper-1.21.11.jar:1.21.11-100-4873e3f]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[02:29:14] [Server thread/INFO]: [ShopChest] Disabling ShopChest v1.12.3`
