### ISSUE TITLE
Shulker Chest implementation

### ISSUE THREAD

**Issue by Imothep80** [EpicEricEE/ShopChest#43]
Hello,

i get this message:

```
[21:28:59 ERROR]: Could not pass event UseBlockEvent to ShopChest v1.11.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at com.sk89q.worldguard.bukkit.util.Events.fireToCancel(Events.java:74) [worldguard-6.1.2.jar:?]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onInventoryOpen(EventAbstractionListener.java:776) [worldguard-6.1.2.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:752) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.EntityPlayer.openContainer(EntityPlayer.java:689) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.BlockShulkerBox.interact(BlockShulkerBox.java:57) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:483) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:897) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_11_R1.block.CraftShulkerBox cannot be cast to org.bukkit.block.Chest
        at de.epiceric.shopchest.listeners.WorldGuardListener.onUseBlock(WorldGuardListener.java:107) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor116.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        ... 29 more
```
I'm not sure if any one try to use the box to create a shop. If not this problem Looks creepy. Do you know about this or Need more Informations? Contact me.

**Comment by EpicEricEE** [comment]
Will be fixed in the next version (4f894dd)
