### ISSUE TITLE
Need help with the error

### ISSUE THREAD

**Issue by Grummpyro** [EpicEricEE/ShopChest#44]
shop is causing this error

[http://pastebin.com/kZvTdBNQ](url)

**Comment by Grummpyro** [comment]
[20:02:41 INFO]: TangoJase issued server command: /back
[20:02:41 INFO]: [WorldGuard] º7WG: ºdTangoJaseº6 left NOTIFY region
[20:02:56 INFO]: Mines are going to reset in 5 minutes.
[20:03:53 WARN]: MarcoValdivia15 moved wrongly!
[20:05:10 ERROR]: Could not pass event UseBlockEvent to ShopChest v1.11.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at com.sk89q.worldguard.bukkit.util.Events.fireToCancel(Events.java:74) [worldguard-6.1.jar:6.1]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onInventoryOpen(EventAbstractionListener.java:726) [worldguard-6.1.jar:6.1]
        at sun.reflect.GeneratedMethodAccessor1077.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:752) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.EntityPlayer.openContainer(EntityPlayer.java:689) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.BlockShulkerBox.interact(BlockShulkerBox.java:57) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:483) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:897) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassCastException
[20:05:44 ERROR]: Could not pass event UseBlockEvent to ShopChest v1.11.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at com.sk89q.worldguard.bukkit.util.Events.fireToCancel(Events.java:74) [worldguard-6.1.jar:6.1]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onInventoryOpen(EventAbstractionListener.java:726) [worldguard-6.1.jar:6.1]
        at sun.reflect.GeneratedMethodAccessor1077.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:752) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.EntityPlayer.openContainer(EntityPlayer.java:689) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.BlockShulkerBox.interact(BlockShulkerBox.java:57) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:483) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:897) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassCastException
[20:06:20 ERROR]: Could not pass event UseBlockEvent to ShopChest v1.11.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at com.sk89q.worldguard.bukkit.util.Events.fireToCancel(Events.java:74) [worldguard-6.1.jar:6.1]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onInventoryOpen(EventAbstractionListener.java:726) [worldguard-6.1.jar:6.1]
        at sun.reflect.GeneratedMethodAccessor1077.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:752) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.EntityPlayer.openContainer(EntityPlayer.java:689) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.BlockShulkerBox.interact(BlockShulkerBox.java:57) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:483) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:897) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassCastException
[20:06:56 INFO]: Mines are going to reset in 1 minutes.
[20:07:57 INFO]: All mines have been reset.
[20:07:57 ERROR]: [ShopChest] No Chest found at specified Location: 3341; 63; -8568
[20:07:57 ERROR]: Could not pass event UseBlockEvent to ShopChest v1.11.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at com.sk89q.worldguard.bukkit.util.Events.fireToCancel(Events.java:74) [worldguard-6.1.jar:6.1]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onInventoryOpen(EventAbstractionListener.java:726) [worldguard-6.1.jar:6.1]
        at sun.reflect.GeneratedMethodAccessor1077.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:752) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.EntityPlayer.openContainer(EntityPlayer.java:689) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.BlockShulkerBox.interact(BlockShulkerBox.java:57) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:483) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:897) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassCastException
[20:08:15 INFO]: MarcoValdivia15 issued server command: /home
[20:08:25 ERROR]: Could not pass event UseBlockEvent to ShopChest v1.11.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at com.sk89q.worldguard.bukkit.util.Events.fireToCancel(Events.java:74) [worldguard-6.1.jar:6.1]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onInventoryOpen(EventAbstractionListener.java:726) [worldguard-6.1.jar:6.1]
        at sun.reflect.GeneratedMethodAccessor1077.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:752) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.EntityPlayer.openContainer(EntityPlayer.java:689) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.BlockShulkerBox.interact(BlockShulkerBox.java:57) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:483) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:897) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-f950f8e-34b2c89]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassCastException
[20:08:37 INFO]: [Grummpy Craft] Warning Ground items will be removed in 60 seconds!

**Comment by EpicEricEE** [comment]
Should be fixed in the next version (4f894dd)

**Comment by plimplum** [comment]
I have the same problem, when coming update?
(Google translator)
