### ISSUE TITLE
Could not pass event UseBlockEvent to Shopchest error

### ISSUE THREAD

**Issue by CyBlue2995** [EpicEricEE/ShopChest#59]
Hello! I just started using your plugin and recently updated to 1.11.2. I came across this error in the console, and was wondering if there was a fix for it. (I am new to owning a server, and plugin management here, so please bear with me :D ) I also looked around on Google and here, but I am not sure how to fix it.

[Server thread/ERROR]: Could not pass event UseBlockEvent to ShopChest v1.11.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at com.sk89q.worldguard.bukkit.util.Events.fireToCancel(Events.java:74) [worldguard-6.2.jar:?]
	at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onInventoryOpen(EventAbstractionListener.java:783) [worldguard-6.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:753) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.EntityPlayer.openContainer(EntityPlayer.java:706) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.BlockShulkerBox.interact(BlockShulkerBox.java:57) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:483) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:904) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_11_R1.block.CraftShulkerBox cannot be cast to org.bukkit.block.Chest
	at de.epiceric.shopchest.listeners.WorldGuardListener.onUseBlock(WorldGuardListener.java:107) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-7d78b81-d5e7885]
	... 29 more
[02:01:14] [Server thread/ERROR]: Could not pass event UseBlockEvent to ShopChest v1.11.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at com.sk89q.worldguard.bukkit.util.Events.fireToCancel(Events.java:74) [worldguard-6.2.jar:?]
	at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onInventoryOpen(EventAbstractionListener.java:783) [worldguard-6.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:753) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.EntityPlayer.openContainer(EntityPlayer.java:706) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.BlockShulkerBox.interact(BlockShulkerBox.java:57) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:483) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:904) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-7d78b81-d5e7885]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_11_R1.block.CraftShulkerBox cannot be cast to org.bukkit.block.Chest
	at de.epiceric.shopchest.listeners.WorldGuardListener.onUseBlock(WorldGuardListener.java:107) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-7d78b81-d5e7885]
	... 29 more

Much appreciated!

Cheers,

CyBlue2995

**Comment by weaves7** [comment]
Hi
He has posted on the spigot discussion that this will be fixed in the next update. Also there are some closed  "issues" here on GitHub that show new commits that take care of it but have not been released yet. Anyway, it happens when someone opens an shulkerbox. I have been ignoring this for a while and have not had any other problems from it.
Hope this helps,
-weaves7

**Comment by CyBlue2995** [comment]
Fantastic! Much appreciated.
