### ISSUE TITLE
i got this error message

### ISSUE THREAD

**Issue by tim12465** [EpicEricEE/ShopChest#75]
` [ShopChest] Plugin ShopChest v1.11.1 generated an exception while executing task 1803674
java.lang.LinkageError: loader constraint violation: when resolving method "de.epiceric.shopchest.utils.UpdateChecker.<init>(Lde/epiceric/shopchest/ShopChest;)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, de/epiceric/shopchest/ShopChest$7, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, de/epiceric/shopchest/utils/UpdateChecker, have different Class objects for the type de/epiceric/shopchest/ShopChest used in the signature
        at de.epiceric.shopchest.ShopChest$7.run(ShopChest.java:266) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_121]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]` i got this on reload
and i also got this ` Could not pass event PlayerInteractEvent to ShopChest v1.11.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:496) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:910) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.StackOverflowError
        at java.io.InputStream.<init>(Unknown Source) ~[?:1.8.0_121]
        at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_121]
        at com.earth2me.essentials.EssentialsConf.load(EssentialsConf.java:65) ~[?:?]
        at com.earth2me.essentials.api.Economy.createNPCFile(Economy.java:47) ~[?:?]
        at com.earth2me.essentials.api.Economy.createNPC(Economy.java:382) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Essentials.createPlayerAccount(Economy_Essentials.java:92) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:150) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]`
what can i do

**Comment by EpicEricEE** [comment]
Can you show me a list _(maybe screenshot?)_ of all plugins you have installed?
